
name: Build and publish package

on:
  create:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set RELEASE_VERSION
      run: |
        RELEASE_VERSION=$(echo ${GITHUB_REF:10}-${GITHUB_SHA:0:7})
        ARCHIVE_BASENAME=sari-web-${RELEASE_VERSION}
        ARCHIVE_NAME=${ARCHIVE_BASENAME}.zip
        echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
        echo "ARCHIVE_BASENAME=$ARCHIVE_BASENAME" >> $GITHUB_ENV
        echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: cached node_modules
      uses: actions/cache@v2
      with:
        path: node_modules/
        key: ${{ runner.os }}.node_modules

    - name: Install Webpack Modules
      run: |
        yarn install
        yarn run build

    - name: Build Lambda Package
      run: |
        set -euo pipefail

        mkdir workdir
        pip install -r <(./gen-requirements.sh) --target workdir/
        cp -pr *.py src common dist workdir
        cd workdir
        printf "app_version = \"$RELEASE_VERSION\"" > version.py
        find . -name \*.so -exec strip --verbose --strip-unneeded --preserve-dates {} \;
        zip -qr9 ../$ARCHIVE_NAME .

    - name: Release It
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ env.ARCHIVE_NAME }}
